FROM node:lts-alpine

WORKDIR '/app'

COPY package.json .

RUN npm install

# no need to copy the source code here, because we will mount the volume
# but we might not need docker-compose for this, so we can copy the source code here
COPY . .

CMD ["npm", "run", "start"]